name: Build & Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: portfolio-478222
          version: 'latest'

      - name: Authenticate Docker
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          IMAGE="us-west1-docker.pkg.dev/portfolio-478222/portfolio/app"
          docker build -t $IMAGE:latest .

      - name: Push Docker image
        run: |
          IMAGE="us-west1-docker.pkg.dev/portfolio-478222/portfolio/app"
          docker push $IMAGE:latest

          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE:latest)
          echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_ENV

      - name: SSH into GCP VM and deploy
        uses: appleboy/ssh-action@v1.1.0
        env:
          IMAGE_DIGEST: ${{ env.IMAGE_DIGEST }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            IMAGE="$IMAGE_DIGEST"

            echo "Pulling latest image..."
            docker pull $IMAGE

            echo "Stopping old container (if running)..."
            docker stop app || true
            docker rm app || true

            echo "Starting new container..."
            docker run -d \
              --name app \
              -p 3000:3000 \
              $IMAGE

            echo "Deployment complete!"
